# config/packages/security.yaml
security:
    password_hashers:
        App\Entity\User:
            algorithm: auto

    providers:
        users_in_database:
            entity:
                class: App\Entity\User
                property: email

    firewalls:
        dev:
            pattern: ^/_(profiler|wdt)
            security: false

        main:
            lazy: true
            provider: users_in_database
            form_login:
                login_path: app_login
                check_path: app_login
                default_target_path: /home
            logout:
                path: app_logout
                target: /home

    access_control:
        - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^/mes-informations, roles: ROLE_USER }

when@test:
    security:
        password_hashers:
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                algorithm: auto
                cost: 4 # Lowest possible value for bcrypt
                time_cost: 3 # Lowest possible value for argon
                memory_cost: 10 # Lowest possible value for argon