security:
    # https://symfony.com/doc/current/security.html#registering-the-user-hashing-passwords
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

    # https://symfony.com/doc/current/security.html#loading-the-user-the-user-provider
    providers:
        users_in_memory: { memory: null }

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            lazy: true
            provider: users_in_memory

            # Connexion avec formulaire
            form_login:
                login_path: accueil         # Page de connexion
                check_path: accueil         # Vérification de l’authentification
            
            # Déconnexion
            logout:
                path: app_logout
                target: accueil             # Redirection après déconnexion
            
            # Activer la mémorisation de session
            remember_me:
                secret: '%kernel.secret%'
                lifetime: 604800            # 1 semaine
                path: /
                always_remember_me: false

    # Contrôle d'accès (règles par URL)
    access_control:
        - { path: ^/accueil, roles: PUBLIC_ACCESS }   # Page d'accueil publique
        - { path: ^/home, roles: ROLE_USER }         # Espace utilisateur
        - { path: ^/detail, roles: ROLE_USER }       # Page protégée

when@test:
    security:
        password_hashers:
            # Simplification du hash pour les tests
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                algorithm: auto
                cost: 4          # Bcrypt minimum
                time_cost: 3     # Argon minimum
                memory_cost: 10  # Argon minimum
