controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

mes_informations:
    path: /mes-informations
    controller: App\Controller\ProfilController::mesInformations

mes_produits:
    path: /mes-produits
    controller: App\Controller\ProfilController::mesProduits

offres_en_attentes:
    path: /offres-en-attentes
    controller: App\Controller\ProfilController::offresEnAttentes

livraison:
    path: /livraison
    controller: App\Controller\ProfilController::livraison

solde:
    path: /solde
    controller: App\Controller\ProfilController::solde

ajout_solde:
    path: /ajout-solde
    controller: App\Controller\ProfilController::ajoutSolde

logout:
    path: /logout

panier:
    path: /panier
    controller: App\Controller\PanierController::index
